### ISSUE TITLE
Additional variables in output from seqAssocGLMM_SPA?

### ISSUE THREAD

**Issue by lauraand1705** [AbbVie-ComputationalGenomics/SAIGEgds#11]
Is it possible to add additional variables to the output from seqAssocGLMM_SPA, i.e. INFO-score if present in the original VCF files?

Thank you for your help.

**Comment by zhengxwen** [comment]
A simple answer is no.
If you use GDS files, use the functions in SeqArray to get the INFO-scores with the variant IDs in the output.
