### ISSUE TITLE
GDS sample IDs problem

### ISSUE THREAD

**Issue by silviaadiz** [AbbVie-ComputationalGenomics/SAIGEgds#2]
Hi!
I fitted the null model and calculated association p-values for one dataset and then tried with the same dataset but changing the sample IDs (.fam file was modified first and then converted into GDS format with the seqArray function). 

Coefficients and variance ratio in the null model aren't the same even though the dataset is, and association results vary too much. 
Only thing that is different between the .gds files is the "sample ID" annotation branch. I repeated the first analysis (with the original sample IDs) three times and I get the same results (which I think are ok), so I believe the issue comes with the new sample ID names. 

I would appreciate any help.
Thank you

**Comment by zhengxw-ab** [comment]
If you have changed the sample IDs in the genotype file, you should also change the sample IDs in the phenotype file according to the change in genotype.
Not sure what is your problem.
